### ISSUE TITLE
not compatible with Flask 1.0

### ISSUE THREAD

**Issue by kennethreitz** [kennethreitz/flask-common#8]
/cc @sigmavirus24

**Comment by jeff00seattle** [comment]
This is breaking `py.test`

```bash
py.test --verbose tests
Traceback (most recent call last):
  File "/usr/local/bin/py.test", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/_pytest/config.py", line 52, in main
    config = _prepareconfig(args, plugins)
  File "/usr/local/lib/python3.6/site-packages/_pytest/config.py", line 163, in _prepareconfig
    pluginmanager=pluginmanager, args=args)
  File "/usr/local/lib/python3.6/site-packages/pluggy/__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 196, in _multicall
    gen.send(outcome)
  File "/usr/local/lib/python3.6/site-packages/_pytest/helpconfig.py", line 68, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.6/site-packages/_pytest/config.py", line 936, in pytest_cmdline_parse
    self.parse(args)
  File "/usr/local/lib/python3.6/site-packages/_pytest/config.py", line 1086, in parse
    self._preparse(args, addopts=addopts)
  File "/usr/local/lib/python3.6/site-packages/_pytest/config.py", line 1048, in _preparse
    self.pluginmanager.load_setuptools_entrypoints('pytest11')
  File "/usr/local/lib/python3.6/site-packages/pluggy/__init__.py", line 397, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/site-packages/_pytest/assertion/rewrite.py", line 213, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "/usr/local/lib/python3.6/site-packages/pytest_httpbin/plugin.py", line 3, in <module>
    from httpbin import app as httpbin_app
  File "/usr/local/lib/python3.6/site-packages/httpbin/__init__.py", line 3, in <module>
    from .core import *
  File "/usr/local/lib/python3.6/site-packages/httpbin/core.py", line 19, in <module>
    from flask_common import Common
  File "/usr/local/lib/python3.6/site-packages/flask_common.py", line 13, in <module>
    from flask.exthook import ExtDeprecationWarning
ModuleNotFoundError: No module named 'flask.exthook'
```
